# Site settings
title: zoltan.mullner.hu
email: zoltan@mullner.hu
description: "TODO: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5896CC #18bc9c
  secondary: 2c3e50
  secondary-dark: 233140

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/mullnerzoltan
  - title: facebook
    url: http://facebook.com/mullner.zoltan
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/mullnerz

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Your disqus shortname, entering this will enable commenting on posts
disqus: mullnerzoltan

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-54316532-1

# Build settings
#markdown: kramdown
#kramdown:
#  input: GFM
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter: pygments
permalink: pretty
